name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.gitignore'
    - '.npmignore'
    - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run build
      run: npm install && npm run build
    - name: Run test
      run: npm run test
